//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahmoudClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Gallery
    {
        public int ID { get; set; }
        [DisplayName("Before")]
        public string BeforePicURL { get; set; }
        [DisplayName("After")]
        public string AfterPicURL { get; set; }
    }
}
